name: Build PouMemoryBot

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Ver estructura del repositorio
        run: |
          echo "Contenido:"
          find . -maxdepth 3 -type f | sort

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "21"

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK
        run: |
          sdkmanager "platform-tools"
          sdkmanager "platforms;android-35"
          sdkmanager "build-tools;35.0.0"

      - name: Entrar al proyecto
        run: |
          cd PouMemoryBot/PouMemoryBot

      - name: Crear Gradle Wrapper
        working-directory: PouMemoryBot/PouMemoryBot
        run: |
          gradle wrapper --gradle-version 8.7

      - name: Compilar APK
        working-directory: PouMemoryBot/PouMemoryBot
        run: |
          chmod +x ./gradlew
          ./gradlew assembleDebug --no-daemon --stacktrace

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: PouMemoryBot-debug
          path: PouMemoryBot/PouMemoryBot/app/build/outputs/apk/debug/*.apk
